// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggwfcekhtzcmhzraurqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdnd2ZjZWtodHpjbWh6cmF1cnFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4OTY0ODcsImV4cCI6MjA3MDQ3MjQ4N30.btPyx5LTlc5TIbjeINDR4Pw0RRE5NosSjL5tzT9W9Ls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});